openapi: 3.0.3
info:
  title: JSONPlaceholder API
  version: 1.0.0
  description: Public fake API for testing

servers:
  - url: https://jsonplaceholder.typicode.com
    description: Production server

paths:
  /posts:
    get:
      summary: Get all posts
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    userId:
                      type: integer
                    id:
                      type: integer
                    title:
                      type: string
                    body:
                      type: string
                  required:
                    - userId
                    - id
                    - title
                    - body

  /users:
    get:
      summary: Get all users
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    username:
                      type: string
                    email:
                      type: string
                    address:
                      type: object
                      properties:
                        street:
                          type: string
                        suite:
                          type: string
                        city:
                          type: string
                        zipcode:
                          type: string
                        geo:
                          type: object
                          properties:
                            lat:
                              type: string
                            lng:
                              type: string
                    phone:
                      type: string
                    website:
                      type: string
                    company:
                      type: object
                      properties:
                        name:
                          type: string
                        catchPhrase:
                          type: string
                        bs:
                          type: string
                  required:
                    - id
                    - name
                    - username
                    - email